Tensors
===
Learn basic PyTorch's Tensors

In [2]:
import torch
import numpy as np

## Tensor Initialization

In [3]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [5]:
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n{x_ones}\n')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor: \n{x_rand}\n')

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.7556, 0.2150],
        [0.8718, 0.0793]])



In [6]:
shape = (2,2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n{rand_tensor}\n')
print(f'Ones Tensor: \n{ones_tensor}\n')
print(f'Zeros Tensor: \n{zeros_tensor}\n')

Random Tensor: 
tensor([[0.5122, 0.2775],
        [0.3139, 0.6475]])

Ones Tensor: 
tensor([[1., 1.],
        [1., 1.]])

Zeros Tensor: 
tensor([[0., 0.],
        [0., 0.]])



## Tensor Attribute

In [7]:
tensor = torch.rand(3,4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations

In [8]:
# move tensor to GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f'Device tensor is stored on: {tensor.device}')
else:
    print('GPU is not available.')

Device tensor is stored on: cuda:0


In [9]:
tensor = torch.ones(2,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
t1 = torch.cat([tensor, tensor, tensor], 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
# compute element-wise product
print(f'tensor.mul(tensor) \n{tensor.mul(tensor)}\n')

# alternative syntax
print(f'tensor * tensor \n{tensor * tensor}')

tensor.mul(tensor) 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
# matrix multiplication
print(f'tensor.matmul(tensor.T) \n{tensor.matmul(tensor.T)}\n')

# alternative syntax
print(f'tensor @ tensor.T \n {tensor @ tensor.T}')

tensor.matmul(tensor.T) 
tensor([[3., 3.],
        [3., 3.]])

tensor @ tensor.T 
 tensor([[3., 3.],
        [3., 3.]])


In [13]:
# in-place operation
print(tensor, '\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

### Tensor to NumPy

In [14]:
t = torch.ones(5)
print(f't: {t}')

n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [15]:
t.add_(3)
print(f't: {t}')
print(f'n: {n}')

t: tensor([4., 4., 4., 4., 4.])
n: [4. 4. 4. 4. 4.]


### NumPy to Tensor

In [16]:
n = np.ones(5)
t = torch.from_numpy(n)

In [17]:
np.add(n, 2, out=n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]
